# -*- coding: utf-8 -*-
"""Python Assignment Lab Session 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IMhKrsBIejiSk4c5MxnmH6ziPtXMPxSR

# New Section
"""

finalscore=0
name=str(input("Enter your name - "))
print("Welcome ",name)
print("Answer the following Questions (Only using integers)")
sum1=int(input("1)   120+180= "))
if sum1==300:
  finalscore=finalscore+1
  print("Correct Answer")
  print("Score is - ",finalscore)
else:
  print("Wrong Answer")
  print("Score is - ",finalscore)
sum2=int(input("2)   12*6 = "))
if sum2==72:
  finalscore=finalscore+2
  print("Correct Answer")
  print("Score is - ",finalscore)
else:
  print("Wrong Answer")
  print("Score is - ",finalscore)
sum3=int(input("3)   98/14 = "))
if sum3==7:
  finalscore=finalscore+3
  print("Correct Answer")
else:
  print("Wrong Answer")
print("Final Score is ",finalscore)
if finalscore==6:
  print("Awesome All The Answers are correct")
elif finalscore>=3:
  print("Nice Try")
elif finalscore>=0:
  print("Better luck next time ")